In [1]:
"""六方结构三、四指数坐标互相转换"""

import numpy as np


def four2three_index(four_index: np.ndarray) -> np.ndarray:
    """将四指数坐标转换为三指数坐标"""

    matrix = np.array(
        [[1.0, -1.0, 0.0, 0.0], [0.0, -1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]
    )

    three_index = matrix @ four_index.T

    return three_index


def three2four_index(three_index: np.ndarray) -> np.ndarray:
    """将三指数坐标转换为四指数坐标"""

    matrix = (
        np.array(
            [[2.0, -1.0, 0.0], [-1.0, 2.0, 0.0], [-1.0, -1.0, 0.0], [0.0, 0.0, 3.0]]
        )
        / 3
    )

    four_index = matrix @ three_index.T
    four_index = np.round(four_index * 3, 1)

    return four_index

In [2]:
four_index = np.array([1, 0, -1, 1])
four2three_index(four_index)

array([ 1., -1.,  1.])

In [6]:
four_index = np.array([1, 1, -2, 0])
four2three_index(four_index)

array([ 0., -3.,  0.])

In [4]:
three_index = np.array([0, 1, 1])
three2four_index(three_index)

array([-1.,  2., -1.,  3.])

In [5]:
three_index = np.array([1, 1, 0])
three2four_index(three_index)

array([ 1.,  1., -2.,  0.])