### 使用 pymatgen ElasticTensor 类计算弹性性质

ElasticTensor 类的实例化参数是 3x3x3x3 的原始矩阵张量，较难手动构造；可使用 `from_voigt()` 方法（继承于 Tensor 类）从 Voigt 格式的张量（6x6 二维矩阵）构造 ElasticTensor 实例。

In [1]:
from pymatgen.analysis.elasticity.elastic import ElasticTensor
import numpy as np

# voigt notation 弹性张量矩阵 6x6
# 立方晶系 金刚石结构 Si 数据 reference: https://vaspkit.com/tutorials.html
elastic_matrix = np.array(
    [
        [1050.640, 126.640, 126.640, 0.000, 0.000, 0.000],
        [126.640, 1050.640, 126.640, 0.000, 0.000, 0.000],
        [126.640, 126.640, 1050.640, 0.000, 0.000, 0.000],
        [0.000, 0.000, 0.000, 559.861, 0.000, 0.000],
        [0.000, 0.000, 0.000, 0.000, 559.861, 0.000],
        [0.000, 0.000, 0.000, 0.000, 0.000, 559.861],
    ]
)
elastic_matrix

array([[1050.64 ,  126.64 ,  126.64 ,    0.   ,    0.   ,    0.   ],
       [ 126.64 , 1050.64 ,  126.64 ,    0.   ,    0.   ,    0.   ],
       [ 126.64 ,  126.64 , 1050.64 ,    0.   ,    0.   ,    0.   ],
       [   0.   ,    0.   ,    0.   ,  559.861,    0.   ,    0.   ],
       [   0.   ,    0.   ,    0.   ,    0.   ,  559.861,    0.   ],
       [   0.   ,    0.   ,    0.   ,    0.   ,    0.   ,  559.861]])

In [2]:
dir(ElasticTensor)

['GPa_to_eV_A3',
 'REDIRECT',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__get_pydantic_core_schema__',
 '__get_pydantic_json_schema__',
 '__get_validators__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor_

In [3]:
et = ElasticTensor.from_voigt(elastic_matrix)
et

ElasticTensor([[[[1050.64     0.       0.   ]
   [   0.     126.64     0.   ]
   [   0.       0.     126.64 ]]

  [[   0.     559.861    0.   ]
   [ 559.861    0.       0.   ]
   [   0.       0.       0.   ]]

  [[   0.       0.     559.861]
   [   0.       0.       0.   ]
   [ 559.861    0.       0.   ]]]


 [[[   0.     559.861    0.   ]
   [ 559.861    0.       0.   ]
   [   0.       0.       0.   ]]

  [[ 126.64     0.       0.   ]
   [   0.    1050.64     0.   ]
   [   0.       0.     126.64 ]]

  [[   0.       0.       0.   ]
   [   0.       0.     559.861]
   [   0.     559.861    0.   ]]]


 [[[   0.       0.     559.861]
   [   0.       0.       0.   ]
   [ 559.861    0.       0.   ]]

  [[   0.       0.       0.   ]
   [   0.       0.     559.861]
   [   0.     559.861    0.   ]]

  [[ 126.64     0.       0.   ]
   [   0.     126.64     0.   ]
   [   0.       0.    1050.64 ]]]])

In [4]:
et.voigt

array([[1050.64 ,  126.64 ,  126.64 ,    0.   ,    0.   ,    0.   ],
       [ 126.64 , 1050.64 ,  126.64 ,    0.   ,    0.   ,    0.   ],
       [ 126.64 ,  126.64 , 1050.64 ,    0.   ,    0.   ,    0.   ],
       [   0.   ,    0.   ,    0.   ,  559.861,    0.   ,    0.   ],
       [   0.   ,    0.   ,    0.   ,    0.   ,  559.861,    0.   ],
       [   0.   ,    0.   ,    0.   ,    0.   ,    0.   ,  559.861]])

In [5]:
et.voigt_symmetrized

ElasticTensor([[[[1050.64     0.       0.   ]
   [   0.     126.64     0.   ]
   [   0.       0.     126.64 ]]

  [[   0.     559.861    0.   ]
   [ 559.861    0.       0.   ]
   [   0.       0.       0.   ]]

  [[   0.       0.     559.861]
   [   0.       0.       0.   ]
   [ 559.861    0.       0.   ]]]


 [[[   0.     559.861    0.   ]
   [ 559.861    0.       0.   ]
   [   0.       0.       0.   ]]

  [[ 126.64     0.       0.   ]
   [   0.    1050.64     0.   ]
   [   0.       0.     126.64 ]]

  [[   0.       0.       0.   ]
   [   0.       0.     559.861]
   [   0.     559.861    0.   ]]]


 [[[   0.       0.     559.861]
   [   0.       0.       0.   ]
   [ 559.861    0.       0.   ]]

  [[   0.       0.       0.   ]
   [   0.       0.     559.861]
   [   0.     559.861    0.   ]]

  [[ 126.64     0.       0.   ]
   [   0.     126.64     0.   ]
   [   0.       0.    1050.64 ]]]])

In [6]:
et.is_symmetric()

False

In [7]:
et.is_voigt_symmetric()

True

In [8]:
# 弹性性质 Dict；也可以单独使用对应属性获取
et.property_dict

{'k_voigt': 434.64000000000004,
 'k_reuss': 434.64000000000004,
 'k_vrh': 434.64000000000004,
 'g_voigt': 520.7166,
 'g_reuss': 516.1302450950266,
 'g_vrh': 518.4234225475133,
 'universal_anisotropy': 0.04443020873664327,
 'homogeneous_poisson': 0.07327739426074353,
 'y_mod': 1112824280151.0627}

In [9]:
et.k_reuss

434.64000000000004

In [10]:
et.k_voigt

434.64000000000004

In [11]:
et.k_vrh

434.64000000000004

In [12]:
et.g_reuss

516.1302450950266

In [13]:
et.g_voigt

520.7166

In [14]:
et.g_vrh

518.4234225475133

In [15]:
et.y_mod

1112824280151.0627

In [16]:
et.universal_anisotropy

0.04443020873664327

In [18]:
et.homogeneous_poisson

0.07327739426074353