### ase 获取 VASP OUTCAR 信息

In [1]:
from ase.io import read

# 不加 index 参数，默认只读取最后一个离子步构型数据
atoms = read("OUTCAR_test")

atoms

Atoms(symbols='Pt19Co19', pbc=True, cell=[[2.807343483, 0.0, 0.0], [-1.403671741, 2.431230773, 0.0], [0.0, 0.0, 78.865859985]], calculator=SinglePointDFTCalculator(...))

In [2]:
from ase.io import read

atoms_list = read("OUTCAR_test", index=":")

atoms_list

[Atoms(symbols='Pt19Co19', pbc=True, cell=[[2.807343483, 0.0, 0.0], [-1.403671741, 2.431230773, 0.0], [0.0, 0.0, 78.865859985]], calculator=SinglePointDFTCalculator(...)),
 Atoms(symbols='Pt19Co19', pbc=True, cell=[[2.807343483, 0.0, 0.0], [-1.403671741, 2.431230773, 0.0], [0.0, 0.0, 78.865859985]], calculator=SinglePointDFTCalculator(...)),
 Atoms(symbols='Pt19Co19', pbc=True, cell=[[2.807343483, 0.0, 0.0], [-1.403671741, 2.431230773, 0.0], [0.0, 0.0, 78.865859985]], calculator=SinglePointDFTCalculator(...)),
 Atoms(symbols='Pt19Co19', pbc=True, cell=[[2.807343483, 0.0, 0.0], [-1.403671741, 2.431230773, 0.0], [0.0, 0.0, 78.865859985]], calculator=SinglePointDFTCalculator(...)),
 Atoms(symbols='Pt19Co19', pbc=True, cell=[[2.807343483, 0.0, 0.0], [-1.403671741, 2.431230773, 0.0], [0.0, 0.0, 78.865859985]], calculator=SinglePointDFTCalculator(...)),
 Atoms(symbols='Pt19Co19', pbc=True, cell=[[2.807343483, 0.0, 0.0], [-1.403671741, 2.431230773, 0.0], [0.0, 0.0, 78.865859985]], calculator=

In [3]:
len(atoms_list)

54

In [4]:
[atoms.get_potential_energy() for atoms in atoms_list]

[-244.97456472,
 -245.00114578,
 -245.00114724,
 -245.00114951,
 -245.00115525,
 -245.00116583,
 -245.00118515,
 -245.0012175,
 -245.00125596,
 -245.00170257,
 -245.00182118,
 -245.00195644,
 -245.00200948,
 -245.00201064,
 -245.00209709,
 -245.00211786,
 -245.00220507,
 -245.00223482,
 -245.00223689,
 -245.00229743,
 -245.00232728,
 -245.00232867,
 -245.00233772,
 -245.00239591,
 -245.00240994,
 -245.00245796,
 -245.0024753,
 -245.0025,
 -245.00253765,
 -245.00256157,
 -245.0025836,
 -245.00260315,
 -245.00260804,
 -245.00262613,
 -245.00262777,
 -245.00264764,
 -245.00264823,
 -245.00266773,
 -245.00267192,
 -245.00269244,
 -245.00270017,
 -245.00271358,
 -245.00271296,
 -245.00272102,
 -245.00271857,
 -245.00272555,
 -245.00272428,
 -245.00273553,
 -245.00273549,
 -245.00273907,
 -245.00274026,
 -245.00274236,
 -245.00274266,
 -245.00274428]

In [5]:
import numpy as np
position_array = np.array([atoms.get_positions() for atoms in atoms_list])
position_array

array([[[ 0.000000e+00,  0.000000e+00,  0.000000e+00],
        [ 1.403670e+00,  8.104100e-01,  2.346480e+00],
        [-0.000000e+00,  1.620820e+00,  4.659220e+00],
        ...,
        [ 1.403670e+00,  8.104100e-01,  7.309069e+01],
        [-0.000000e+00,  1.620820e+00,  7.495485e+01],
        [ 1.403670e+00,  8.104100e-01,  7.679611e+01]],

       [[-0.000000e+00,  0.000000e+00,  2.160000e-03],
        [ 1.403670e+00,  8.104100e-01,  2.350690e+00],
        [-0.000000e+00,  1.620820e+00,  4.659010e+00],
        ...,
        [ 1.403670e+00,  8.104100e-01,  7.308896e+01],
        [-0.000000e+00,  1.620820e+00,  7.495424e+01],
        [ 1.403670e+00,  8.104100e-01,  7.678980e+01]],

       [[-0.000000e+00,  0.000000e+00,  2.160000e-03],
        [ 1.403670e+00,  8.104100e-01,  2.350710e+00],
        [-0.000000e+00,  1.620820e+00,  4.659010e+00],
        ...,
        [ 1.403670e+00,  8.104100e-01,  7.308896e+01],
        [-0.000000e+00,  1.620820e+00,  7.495423e+01],
        [ 1.403670e+00

In [6]:
force_array = np.array([atoms.get_forces() for atoms in atoms_list])
force_array

array([[[-0.00000e+00,  0.00000e+00,  4.47260e-02],
        [-0.00000e+00,  0.00000e+00,  8.74540e-02],
        [ 0.00000e+00, -0.00000e+00, -4.32500e-03],
        ...,
        [-0.00000e+00, -0.00000e+00, -3.58050e-02],
        [-0.00000e+00,  0.00000e+00, -1.27040e-02],
        [-0.00000e+00,  0.00000e+00, -1.30801e-01]],

       [[ 0.00000e+00,  0.00000e+00, -1.17090e-02],
        [ 0.00000e+00, -0.00000e+00,  3.65560e-02],
        [-0.00000e+00,  0.00000e+00,  1.77080e-02],
        ...,
        [-0.00000e+00, -0.00000e+00, -1.21300e-03],
        [ 0.00000e+00,  0.00000e+00,  3.41440e-02],
        [ 0.00000e+00, -0.00000e+00, -5.81130e-02]],

       [[ 0.00000e+00, -0.00000e+00, -1.18100e-02],
        [ 0.00000e+00, -0.00000e+00,  3.63880e-02],
        [ 0.00000e+00, -0.00000e+00,  1.77780e-02],
        ...,
        [ 0.00000e+00, -0.00000e+00, -1.19900e-03],
        [-0.00000e+00,  0.00000e+00,  3.41530e-02],
        [-0.00000e+00, -0.00000e+00, -5.79640e-02]],

       ...,

      

In [7]:
ediffg = -0.001

F = np.sqrt(np.power(force_array, 2).sum(axis=-1))
# 查看哪些离子步中的原子受力大于 ediffg；True 表示受力大于 ediffg
boolen_array = F > np.abs(ediffg)
boolen_array

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [False, False,  True, ..., False,  True, False],
       [False, False,  True, ..., False,  True, False],
       [False, False, False, ..., False, False, False]])